import { useState, type FormEvent } from "react"
import { LoaderCircleIcon, PlusIcon } from "lucide-react"
import { useTranslation } from "react-i18next"

import { Button } from "@/components/ui/button"
import { Field, FieldDescription, FieldError, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetFooter,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet"
import type { RegisterApplicationInput, Organization } from "@/domain/contracts"
import { registerApplication } from "@/lib/product-api"

const initialInput: RegisterApplicationInput = {
  displayName: "",
  ownerOrganizationId: "",
}

export function RegisterApplicationSheet({
  tenantId,
  organizations,
  onRegistered,
}: {
  tenantId: string
  organizations: Organization[]
  onRegistered: () => Promise<void>
}) {
  const { t } = useTranslation()
  const [open, setOpen] = useState(false)
  const [input, setInput] = useState(initialInput)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState("")

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setSubmitting(true)
    setError("")
    try {
      await registerApplication(tenantId, input)
      setInput(initialInput)
      setOpen(false)
      await onRegistered()
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : t("Application registration failed"))
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <Sheet open={open} onOpenChange={setOpen}>
      <SheetTrigger asChild>
        <Button disabled={!organizations.length}>
          <PlusIcon data-icon="inline-start" />
          {t("Register Application")}
        </Button>
      </SheetTrigger>
      <SheetContent className="w-full overflow-y-auto sm:max-w-xl">
        <form className="flex min-h-full flex-col" onSubmit={submit}>
          <SheetHeader className="border-b px-6 py-5">
            <SheetTitle>{t("Register Application Subject")}</SheetTitle>
            <SheetDescription>
              {t("Create a unique Application identity owned by an Organization. The Application ID is generated by GenioOne.")}
            </SheetDescription>
          </SheetHeader>
          <FieldGroup className="p-6">
            <Field data-invalid={Boolean(error)}>
              <FieldLabel htmlFor="application-display-name">{t("Display name")}</FieldLabel>
              <Input
                id="application-display-name"
                value={input.displayName}
                onChange={(event) => setInput((current) => ({ ...current, displayName: event.target.value }))}
                placeholder={t("Payment Worker")}
                aria-invalid={Boolean(error)}
                required
              />
              <FieldDescription>{t("Human-readable name shown in access requests and audit views.")}</FieldDescription>
            </Field>
            <Field data-invalid={Boolean(error)}>
              <FieldLabel htmlFor="application-owner-organization">{t("Owner Organization")}</FieldLabel>
              <Select
                value={input.ownerOrganizationId}
                onValueChange={(ownerOrganizationId) => setInput((current) => ({ ...current, ownerOrganizationId }))}
                required
              >
                <SelectTrigger id="application-owner-organization" aria-invalid={Boolean(error)}>
                  <SelectValue placeholder={t("Select an Owner Organization")} />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    {organizations.map((organization) => (
                      <SelectItem key={organization.organization_id} value={organization.organization_id}>
                        {organization.display_name}
                      </SelectItem>
                    ))}
                  </SelectGroup>
                </SelectContent>
              </Select>
              <FieldDescription>{t("Only verified members of this Organization may act for the Application.")}</FieldDescription>
              {error ? <FieldError>{t(error)}</FieldError> : null}
            </Field>
          </FieldGroup>
          <SheetFooter className="mt-auto border-t bg-background px-6 py-4">
            <Button type="button" variant="outline" onClick={() => setOpen(false)}>
              {t("Cancel")}
            </Button>
            <Button type="submit" disabled={submitting || !input.ownerOrganizationId}>
              {submitting ? <LoaderCircleIcon data-icon="inline-start" className="animate-spin" /> : null}
              {t(submitting ? "Registering…" : "Register Application")}
            </Button>
          </SheetFooter>
        </form>
      </SheetContent>
    </Sheet>
  )
}
