create table genio_one_distillation_markers (
  tenant_id text not null,
  marker_id text not null,
  owner_subject_id text not null,
  bot_id text not null,
  thread_id text not null,
  turn_ids jsonb not null,
  source_revision text not null,
  content_digest text not null,
  scope_hint text not null,
  sensitivity text not null,
  knowledge_type text not null,
  representation text not null,
  classifier_version text not null,
  extractor_version text not null,
  evidence jsonb not null,
  excerpt_truncated boolean not null,
  history_state text not null,
  processing_state text not null,
  attempts integer not null,
  not_before bigint not null,
  lease_owner text,
  lease_token text,
  lease_until bigint,
  workspace_id text,
  last_error text,
  created_at bigint not null,
  updated_at bigint not null,
  constraint genio_one_distillation_markers_pkey primary key (tenant_id, marker_id),
  constraint genio_one_distillation_markers_idempotency unique (tenant_id, owner_subject_id, bot_id, thread_id, source_revision, extractor_version),
  constraint genio_one_distillation_markers_turn_ids_check check (jsonb_typeof(turn_ids) = 'array'),
  constraint genio_one_distillation_markers_evidence_check check (jsonb_typeof(evidence) = 'array'),
  constraint genio_one_distillation_markers_scope_check check (scope_hint in ('product', 'department', 'process', 'shared', 'customer_project')),
  constraint genio_one_distillation_markers_sensitivity_check check (sensitivity in ('standard', 'restricted')),
  constraint genio_one_distillation_markers_type_check check (knowledge_type in ('FACT', 'PROCEDURE', 'DECISION', 'SKILL')),
  constraint genio_one_distillation_markers_representation_check check (representation in ('HUMAN', 'MACHINE', 'BOTH', 'EVIDENCE_ONLY')),
  constraint genio_one_distillation_markers_history_check check (history_state in ('READY', 'WAITING_FOR_HISTORY')),
  constraint genio_one_distillation_markers_state_check check (processing_state in ('PENDING', 'WAITING_FOR_HISTORY', 'PROCESSING', 'CANDIDATE_CREATED', 'FILTERED_OUT', 'FAILED')),
  constraint genio_one_distillation_markers_attempts_check check (attempts >= 0),
  constraint genio_one_distillation_markers_digest_check check (content_digest ~ '^[a-f0-9]{64}$' and source_revision ~ '^[a-f0-9]{64}$'),
  constraint genio_one_distillation_markers_classifier_check check (classifier_version = 'jev-distillation-1' and extractor_version = 'timeline-body-1')
);

create index genio_one_distillation_markers_claim_idx
  on genio_one_distillation_markers (tenant_id, owner_subject_id, bot_id, processing_state, not_before);

create table genio_one_knowledge_candidates (
  tenant_id text not null,
  knowledge_id text not null,
  marker_id text not null,
  owner_subject_id text not null,
  workspace_id text,
  scope text not null,
  knowledge_type text not null,
  representation text not null,
  sensitivity text not null,
  review_state text not null,
  content_digest text not null,
  provenance jsonb not null,
  reviewed_by text,
  reviewed_at bigint,
  created_at bigint not null,
  updated_at bigint not null,
  constraint genio_one_knowledge_candidates_pkey primary key (tenant_id, knowledge_id),
  constraint genio_one_knowledge_candidates_marker_unique unique (tenant_id, marker_id),
  constraint genio_one_knowledge_candidates_marker_fkey foreign key (tenant_id, marker_id)
    references genio_one_distillation_markers (tenant_id, marker_id),
  constraint genio_one_knowledge_candidates_provenance_check check (jsonb_typeof(provenance) = 'object'),
  constraint genio_one_knowledge_candidates_scope_check check (scope in ('product', 'department', 'process', 'shared', 'customer_project')),
  constraint genio_one_knowledge_candidates_sensitivity_check check (sensitivity in ('standard', 'restricted')),
  constraint genio_one_knowledge_candidates_type_check check (knowledge_type in ('FACT', 'PROCEDURE', 'DECISION', 'SKILL')),
  constraint genio_one_knowledge_candidates_representation_check check (representation in ('HUMAN', 'MACHINE', 'BOTH', 'EVIDENCE_ONLY')),
  constraint genio_one_knowledge_candidates_review_check check (review_state in ('PENDING_REVIEW', 'APPROVED', 'REJECTED')),
  constraint genio_one_knowledge_candidates_digest_check check (content_digest ~ '^[a-f0-9]{64}$')
);
